name: Publish External Update

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (owner/name)'
        required: true
        type: string
      ref:
        description: 'Branch/tag/commit to read from (optional)'
        required: false
        type: string
      module_path:
        description: 'Subdirectory within repo (optional)'
        required: false
        type: string
      post_title:
        description: 'Post title'
        required: true
        type: string
      post_date:
        description: 'Post date (YYYY-MM-DD, optional)'
        required: false
        type: string
      categories:
        description: 'Categories (comma-separated, optional)'
        required: false
        type: string
      tags:
        description: 'Tags (comma-separated, optional)'
        required: false
        type: string
      extra_content:
        description: 'Additional content/learnings (markdown, optional)'
        required: false
        type: string
      custom_summary:
        description: 'Custom summary (optional)'
        required: false
        type: string
      dry_run:
        description: 'Dry run (preview only)'
        required: false
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 markdown

      - name: Generate post
        env:
          SOURCE_REPO: ${{ github.event.inputs.source_repo }}
          REF: ${{ github.event.inputs.ref }}
          MODULE_PATH: ${{ github.event.inputs.module_path }}
          POST_TITLE: ${{ github.event.inputs.post_title }}
          POST_DATE: ${{ github.event.inputs.post_date }}
          CATEGORIES: ${{ github.event.inputs.categories }}
          TAGS: ${{ github.event.inputs.tags }}
          EXTRA_CONTENT: ${{ github.event.inputs.extra_content }}
          CUSTOM_SUMMARY: ${{ github.event.inputs.custom_summary }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          SOURCE_REPOS_TOKEN: ${{ secrets.SOURCE_REPOS_TOKEN || '' }}
        run: |
          python scripts/generate_post.py

      - name: Upload artifact (dry run)
        if: ${{ github.event.inputs.dry_run == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: generated-post
          path: generated_post.md

      - name: Create branch and PR
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          # Set up git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create branch
          BRANCH_NAME="manual-update/$(echo "$POST_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')-$(date +%Y%m%d)"
          git checkout -b "$BRANCH_NAME"
          
          # Move generated post to _posts directory
          POST_FILENAME="$(date +%Y-%m-%d)-$(echo "$POST_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g').md"
          mv generated_post.md "_posts/$POST_FILENAME"
          
          # Commit and push
          git add "_posts/$POST_FILENAME"
          git commit -m "Add post: $POST_TITLE"
          git push origin "$BRANCH_NAME"
          
          # Create PR
          gh pr create \
            --title "Add post: $POST_TITLE" \
            --body "Generated post from $SOURCE_REPO$([ -n "$MODULE_PATH" ] && echo "/$MODULE_PATH" || echo "")" \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
